version: "3.9"

services:
  neo4j:
    image: neo4j:2025.06.2
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "${NEO4J_HOST}:${NEO4J_BROWSER_PORT}:7474"
      - "${NEO4J_HOST}:${NEO4J_BOLT_PORT}:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: